spring:
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
  jwt:
    secret: k9McIikyWC2xy7f0Rg3rIIlMn8hUBJnyLj8c

server:
  tomcat:
    max-swallow-size: -1

#Model Location
mybatis:
  type-aliases-package: com.eura.web.model.DTO

#Xml Location
  mapper-locations: classpath:sqlmap/*.xml
  configuration:
    jdbc-type-for-null: null
