server:
  port: 10000

#Oracle DataSource
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://eura-maria-db.cmjphsu1czot.ap-northeast-2.rds.amazonaws.com:3306/eura_db
    username: eura_user
    password: eura_pass

#업로드 디렉토리는 협의 후 확정
file:
  upload-dir: /Users/apple/Desktop/EURAfiles
#  upload-dir: /Users/abeki/workspace/FACT/file_store
mail:
  passwd: mailpass