spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://eura-db.cxmubqzajvkd.ap-northeast-2.rds.amazonaws.com:3306/eura_db
    username: euradb
    password: db!#221104fk&$%^

#업로드 디렉토리는 협의 후 확정
file:
  upload-dir: /home/ec2-user/EURA-upload

#운영은 에러 로그 보이게 하기
logging:
  level:
    root: warn
    com:
      eura: debug
  file:
    path: /Users/ec2-user/EURA/logs
    max-history: 7

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0
  auto:
    load:
      popular:
        drivers: false

mail:
  passwd: "foicfoic22!"

domain: https://api.eura.site
w3domain: https://eura.site
filedomain: https://file.eura.site/upload
voddomain: https://vod.eura.site