server:
  port: 10000

#Oracle DataSource
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://eura-maria-db.cmjphsu1czot.ap-northeast-2.rds.amazonaws.com:3306/eura_db
    username: eura_user
    # db!#221104fk&$%^
    password: eura_pass

#업로드 디렉토리는 협의 후 확정
file:
  upload-dir: /opt/server/upload/
mail:
  passwd: mailpass