spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  jwt:
    secret: k9McIikyWC2xy7f0Rg3rIIlMn8hUBJnyLj8c
  web:
    resources:
      add-mappings: true
      static-locations: classpath:static/

#Model Location
mybatis:
  type-aliases-package: com.eura.web.model.DTO

#Xml Location
  mapper-locations: classpath:sqlmap/*.xml
  configuration:
    jdbc-type-for-null: null
