server:
  port: 10000

#Oracle DataSource
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://euradb.cxmubqzajvkd.ap-northeast-2.rds.amazonaws.com:3306/eura_db
    username: eura_user
    password: db!#221104fk&$%^

#업로드 디렉토리는 협의 후 확정
file:
  upload-dir: /upload/
mail:
  passwd: mailpass