ALTER TABLE `TB_MEETING` CHANGE `MT_STATUS` TINYINT(1)  NULL  DEFAULT 0  COMMENT '미팅룸 상태 - 0:비공개, 1:공개, 2:취소, 3:삭제';

ALTER TABLE `TB_MEETING` ADD `IS_LIVE` TINYINT(1)  NULL  DEFAULT 0  COMMENT '미팅 시작 여부 - 0:아니오, 1:예' AFTER `MT_STATUS`;

ALTER TABLE `TB_MEETING` CHANGE `MT_REMIND_WEEK` VARCHAR(20)  CHARACTER SET utf8mb4  COLLATE utf8mb4_general_ci  NULL  DEFAULT NULL  COMMENT '반복요일 - 일,월,화,수,목,금,토 = 1,2,3,4,5,6,7';

ALTER TABLE `TB_MEETING` ADD `IS_FINISH` TINYINT(1)  NULL  DEFAULT 0  COMMENT '미팅 종료 여부 - 0:아니오, 1:예' AFTER `IS_LIVE`;

ALTER TABLE `TB_MEETING_USER_JOIN` ADD `IS_ALIVE` TINYINT(1)  NULL  DEFAULT 0  COMMENT '감정분석 상태 - 0:미진행, 1:진행' AFTER `JOIN_DT`;

ALTER TABLE `TB_MEETING` ADD `IS_FINISH_DT` DATETIME  NULL  COMMENT '미팅 종료 일시' AFTER `IS_FINISH`;
ALTER TABLE `TB_MEETING` ADD `IS_LIVE_DT` DATETIME  NULL  COMMENT '미팅 시작 일시' AFTER `IS_LIVE`;

ALTER TABLE `TB_MEETING_USER_JOIN` ADD `ZUID` VARCHAR(100)  NULL  DEFAULT NULL  COMMENT 'ZOOM User ID'  AFTER `IS_ALIVE`;

ALTER TABLE `TB_PROFILE_INFO` ADD `LAST_UPD_DT` DATETIME  NULL  DEFAULT NULL  ON UPDATE CURRENT_TIMESTAMP  COMMENT '수정 일시'  AFTER `REG_DT`;

ALTER TABLE `TB_MEETING_MOVIE_FILE` ADD `FILE_NO` INT(11)  NULL  DEFAULT 0  COMMENT '파일 순서' AFTER `IDX_MEETING`;

ALTER TABLE `TB_MEETING_MOVIE_FILE` ADD `DURATION` INT(11)  NULL  DEFAULT 0 DEFAULT NULL  COMMENT '재생시간' AFTER `FILE_SIZE`;

ALTER TABLE `TB_MEETING_MOVIE_FILE` ADD `RECORD_DT` DATETIME  NULL  DEFAULT NULL COMMENT '녹화 시작 시간' AFTER `DURATION`;
