ALTER TABLE `TB_MEETING` ADD `IS_LIVE` `IS_LIVE` TINYINT(1)  NULL  DEFAULT 0  COMMENT '미팅 시작 여부 - 0:아니오, 1:예';
ALTER TABLE `TB_MEETING` ADD `MT_STATUS` `MT_STATUS` TINYINT(1)  NULL  DEFAULT 0  COMMENT '미팅룸 상태 - 0:비공개, 1:공개, 2:취소, 3:삭제';

ALTER TABLE `TB_MEETING` ADD `MT_REMIND_WEEK` `MT_REMIND_WEEK` VARCHAR(20)  CHARACTER SET utf8mb4  COLLATE utf8mb4_general_ci  NULL  DEFAULT NULL  COMMENT '반복요일 - 일,월,화,수,목,금,토 = 1,2,3,4,5,6,7';

ALTER TABLE `TB_MEETING` ADD `IS_FINISH` `IS_FINISH` TINYINT(1)  NULL  DEFAULT 0  COMMENT '미팅 종료 여부 - 0:아니오, 1:예';
